#!/usr/bin/env python3
"""
Cybersecurity Roadmap Repository Builder
=========================================
Generates the folder/file architecture for a cybersecurity learning portfolio.

Usage:
    python build_roadmap.py

Idempotent: safe to re-run. Existing topic files are not overwritten.
"""

from __future__ import annotations

import re
import unicodedata
from pathlib import Path

ROOT = Path(__file__).parent.resolve()

# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

# Turkish -> English character map (for any stray Turkish letters)
TR_MAP = str.maketrans({
    "ç": "c", "Ç": "C",
    "ğ": "g", "Ğ": "G",
    "ı": "i", "İ": "I",
    "ö": "o", "Ö": "O",
    "ş": "s", "Ş": "S",
    "ü": "u", "Ü": "U",
})

# Symbols that should become readable words instead of being stripped.
# Spaces wrap each replacement so adjacent characters stay properly separated.
SYMBOL_WORDS = {
    "+": " plus ",
    "#": " sharp ",
    "&": " and ",
}

FILE_TEMPLATE = """# {title}

## 1. Summary (Theory)

_Add concise theory, definitions, and key concepts here._

## 2. Commands (Cheatsheet)

```bash
# Add tools, commands, and useful one-liners here.
```

## 3. Lab Output (Proof)

_Add screenshots, command output, or write-ups proving hands-on practice._
"""

README_TEMPLATE = """# Cybersecurity Learning Roadmap and Portfolio

This repository is a **comprehensive cybersecurity learning roadmap and portfolio**.
It documents my journey from core IT fundamentals all the way to advanced
offensive and defensive security operations.

Each topic is documented as a Markdown note structured around three sections:

1. **Summary (Theory)** - concept overview, definitions, and key ideas.
2. **Commands (Cheatsheet)** - tools, commands, and useful one-liners.
3. **Lab Output (Proof)** - hands-on results, screenshots, and findings.

## Roadmap Stages

| # | Stage |
|---|-------|
{stage_table}

## How to Use

- Browse a stage folder and pick a topic file to study.
- Treat each `.md` file as both a learning log and a quick-reference cheatsheet.
- Add your own labs, notes, and proofs as you progress.

## Auto-Generation

The architecture in this repository was generated by `build_roadmap.py`.
Re-running the script is safe; it will create any missing folders/files
without overwriting your existing notes.

> _"The expert in anything was once a beginner."_
"""


def sanitize_name(name: str) -> str:
    """Convert a topic name into a filesystem-safe identifier."""
    # Drop anything in parentheses (e.g. Turkish translations).
    name = re.sub(r"\([^)]*\)", "", name).strip()
    # Turkish -> English
    name = name.translate(TR_MAP)
    # Strip remaining diacritics / non-ASCII.
    name = unicodedata.normalize("NFKD", name).encode("ascii", "ignore").decode("ascii")
    # Replace special symbols with readable equivalents.
    for symbol, word in SYMBOL_WORDS.items():
        name = name.replace(symbol, word)
    # Replace remaining punctuation with whitespace.
    name = re.sub(r"[^\w\s-]", " ", name)
    # Collapse whitespace -> underscores.
    name = re.sub(r"\s+", "_", name.strip())
    # Collapse repeated underscores.
    name = re.sub(r"_+", "_", name)
    return name.strip("_")


# ---------------------------------------------------------------------------
# Roadmap definition
# ---------------------------------------------------------------------------
# Each stage is a tuple: (stage_name, [topics]).
# A topic is either:
#   - str  -> creates a Markdown file.
#   - dict -> creates a subfolder; the value is a list of nested topics.

ROADMAP: list[tuple[str, list]] = [
    ("IT and OS Fundamentals", [
        "Computer Hardware Components",
        "Connection Types and their Function",
        "OS Independent Troubleshooting",
        {"Popular Suites": [
            "MS Office Suite",
            "Google Suite",
            "iCloud",
        ]},
        {"Operating Systems": [
            "Windows",
            "Linux",
            "MacOS",
            "Installation and Configuration",
            "Different Versions and Differences",
            "Navigating using GUI and CLI",
            "Understanding Permissions",
            "Installing Software and Applications",
            "Performing CRUD on Files",
            "OS Troubleshooting",
            "Common Commands",
        ]},
        {"Virtualization": [
            "Basics of Virtualization",
            "Hypervisor",
            "HostOS",
            "GuestOS",
            "Virtual Machine",
            "VMware",
            "VirtualBox",
            "ESXi",
            "Proxmox",
        ]},
    ]),

    ("Networking and Protocols", [
        {"Basics of Computer Networking": [
            "WiFi",
            "Bluetooth",
            "NFC",
            "Infrared",
        ]},
        "OSI Model",
        {"Network Topologies": [
            "Star Topology",
            "Ring Topology",
            "Mesh Topology",
            "Bus Topology",
            "MAN",
            "LAN",
            "WAN",
            "WLAN",
        ]},
        {"Network Protocols": [
            "HTTP and HTTPS",
            "SSL and TLS",
            "SSH",
            "RDP",
            "FTP",
            "SFTP",
        ]},
        {"IP Terminology": [
            "Public vs Private IP Addresses",
            "Basics of Subnetting",
            "Subnet Mask",
            "CIDR",
            "Localhost",
            "Loopback",
            "Default Gateway",
        ]},
        {"Networking Terminology": [
            "IP",
            "NAT",
            "ARP",
            "DHCP",
            "DNS",
            "VLAN",
            "DMZ",
            "Router",
            "Switch",
            "VPN",
        ]},
        {"Core Network Services": [
            "DHCP Service",
            "DNS Service",
            "NTP",
            "IPAM",
        ]},
        "Common Ports and their Uses",
        "SSL and TLS Basics",
        "Basics of NAS and SAN",
        {"Authentication Methodologies": [
            "Local Auth",
            "Certificates",
            "Kerberos",
            "RADIUS",
            "LDAP",
            "SSO",
        ]},
    ]),

    ("Programming and Cloud Computing", [
        {"Programming Skills": [
            "Python",
            "Go",
            "JavaScript",
            "C++",
            "Bash",
            "PowerShell",
        ]},
        {"Cloud Concepts": [
            "Security in the Cloud",
            "Cloud Deployment Basics",
            "Cloud vs On Premises",
            "Infrastructure as Code",
            "Serverless Architecture",
        ]},
        {"Cloud Service Models": [
            "SaaS",
            "PaaS",
            "IaaS",
        ]},
        {"Cloud Deployment Models": [
            "Private Cloud",
            "Public Cloud",
            "Hybrid Cloud",
        ]},
        {"Common Cloud Environments": [
            "AWS",
            "GCP",
            "Azure",
        ]},
        {"Common Cloud Storage": [
            "S3",
            "Dropbox",
            "Box",
            "OneDrive",
            "Google Drive",
            "iCloud Storage",
        ]},
    ]),

    ("Cybersecurity Fundamentals and Concepts", [
        "CIA Triad",
        "Definition of Risk",
        "Backups and Resiliency",
        {"Basics of Cryptography": [
            "Salting",
            "Hashing",
            "Key Exchange",
            "PKI Public Key Infrastructure",
            "Private vs Public Keys",
            "Obfuscation",
        ]},
        "Authentication vs Authorization",
        "MFA and 2FA",
        "Perimeter vs DMZ vs Segmentation",
        "Zero Trust Core Concepts",
        "Handshakes",
        "Isolation Concept",
        {"Operating System Hardening": [
            "Hardening Concepts",
            "MAC based Access Control",
            "NAC based Access Control",
            "Port Blocking",
            "Group Policy",
            "Sinkholes",
            "ACLs",
            "Patching",
            "Jump Server",
            "Endpoint Security",
        ]},
        {"Secure vs Unsecure Protocols": [
            "FTP vs SFTP",
            "SSL vs TLS Comparison",
            "IPSEC",
            "DNSSEC",
            "LDAPS",
            "SRTP",
            "S/MIME",
        ]},
        {"Security Terms and Tools": [
            "Antivirus and Antimalware",
            "EDR",
            "DLP",
            "ACL Security",
            "Firewall and NextGen Firewall",
            "HIPS",
            "NIDS",
            "NIPS",
            "Host Based Firewall",
            "Sandboxing",
            "EAP vs PEAP",
            "WPS",
            "WPA vs WPA2 vs WPA3 vs WEP",
        ]},
    ]),

    ("Security Tools and Troubleshooting", [
        {"Troubleshooting Tools": [
            "nslookup",
            "iptables",
            "ipconfig",
            "netstat",
            "ping",
            "dig",
            "arp",
            "route",
            "nmap",
            "tcpdump",
            "tracert",
        ]},
        "Packet Sniffers and Protocol Analyzers",
        "Port Scanners",
        {"Incident Response and Discovery Tools": [
            "curl",
            "hping",
            "cat",
            "dd",
            "head",
            "grep",
            "wireshark",
            "winhex",
            "memdump",
            "FTK Imager",
            "autopsy",
            "tail",
        ]},
        {"Common Hacking Distributions": [
            "Kali Linux",
            "ParrotOS",
        ]},
        {"Common Web Tools": [
            "VirusTotal",
            "Joe Sandbox",
            "any.run",
            "urlvoid",
            "urlscan",
            "WHOIS",
        ]},
        {"Living Off the Land": [
            "LOLBAS",
            "GTFOBINS",
            "WADCOMS",
        ]},
    ]),

    ("Attacks and Vulnerabilities", [
        "Malware Types and How They Work",
        {"Threat Classification": [
            "Zero Day Threats",
            "Known vs Unknown Threats",
            "Advanced Persistent Threat APT",
        ]},
        {"Social Engineering": [
            "Reconnaissance",
            "Impersonation",
            "Phishing",
            "Vishing",
            "Whaling",
            "Smishing",
            "Spam vs Spim",
            "Shoulder Surfing",
            "Dumpster Diving",
            "Tailgating",
        ]},
        {"Attack Types and Differences": [
            "Watering Hole Attack",
            "Drive by Attack",
            "Typo Squatting",
            "Brute Force vs Password Spray",
            "DoS vs DDoS",
            "Man in the Middle MITM",
        ]},
        {"Common Attacks": [
            "Spoofing",
            "Evil Twin",
            "DNS Poisoning",
            "Deauth Attack",
            "VLAN Hopping",
            "Rogue Access Point",
            "Buffer Overflow",
            "Memory Leak",
            "Replay Attack",
            "Pass the Hash",
            "Directory Traversal",
        ]},
        {"Web Based Attacks OWASP Top 10": [
            "SQL Injection",
            "XSS Cross Site Scripting",
            "CSRF Cross Site Request Forgery",
        ]},
        "Privilege Escalation",
        "Zero Day Attacks",
    ]),

    ("Defense Frameworks and Operations", [
        "Defense in Depth",
        "Basics of IDS and IPS",
        "Honeypots",
        "Blue Red and Purple Teams",
        "False Positive False Negative True Positive True Negative",
        "Threat Intel and OSINT Basics",
        {"Security Frameworks": [
            "MITRE ATT&CK",
            "Diamond Model",
            "Kill Chain",
            "Cyber Kill Chain",
        ]},
        {"Common Standards": [
            "ISO",
            "NIST",
            "RMF",
            "CIS",
            "CSF",
        ]},
        "Compliance and Auditor Roles",
        "SIEM",
        "SOAR",
        {"Logs to Know": [
            "Event Logs",
            "Syslogs",
            "Netflow",
            "Packet Captures",
            "Firewall Logs",
        ]},
        {"Incident Response Process": [
            "Preparation",
            "Identification",
            "Containment",
            "Eradication",
            "Recovery",
            "Lessons Learned",
        ]},
        {"Audience Understanding": [
            "Stakeholders",
            "HR",
            "Legal",
            "Compliance",
            "Management",
        ]},
        "Runbooks Concept",
        "Basics of Forensics",
        "Basics of Threat Hunting",
        "Basics of Vulnerability Management",
        "Basics of Reverse Engineering",
        "Common Exploit Frameworks",
        "Common Hacking Tools",
        "Penetration Testing Rules of Engagement",
    ]),

    ("Practice and Certifications", [
        {"CTF Platforms": [
            "HackTheBox",
            "TryHackMe",
            "VulnHub",
            "picoCTF",
            "SANS Holiday Hack Challenge",
        ]},
        {"Beginner Certifications": [
            "CompTIA A+",
            "CompTIA Linux+",
            "CompTIA Network+",
            "CCNA",
            "CompTIA Security+",
        ]},
        {"Advanced Certifications": [
            "CEH",
            "CISA",
            "CISM",
            "GSEC",
            "GPEN",
            "GWAPT",
            "GIAC",
            "OSCP",
            "CREST",
            "CISSP",
        ]},
        "Keep Learning",
    ]),
]


# ---------------------------------------------------------------------------
# Build logic
# ---------------------------------------------------------------------------

def build_topic(parent: Path, topic) -> tuple[int, int]:
    """Recursively materialize a topic (file or subfolder).

    Returns (files_created, folders_created).
    """
    files_created = 0
    folders_created = 0

    if isinstance(topic, dict):
        (folder_name, items), = topic.items()
        folder_path = parent / sanitize_name(folder_name)
        if not folder_path.exists():
            folders_created += 1
        folder_path.mkdir(parents=True, exist_ok=True)
        for item in items:
            f, d = build_topic(folder_path, item)
            files_created += f
            folders_created += d
    elif isinstance(topic, str):
        file_path = parent / f"{sanitize_name(topic)}.md"
        if not file_path.exists():
            file_path.write_text(
                FILE_TEMPLATE.format(title=topic),
                encoding="utf-8",
            )
            files_created += 1
    else:
        raise TypeError(f"Unsupported topic type: {type(topic)!r}")

    return files_created, folders_created


def main() -> None:
    total_files = 0
    total_folders = 0
    stage_table_rows: list[str] = []

    for index, (stage_name, topics) in enumerate(ROADMAP, start=1):
        stage_folder_name = f"{index:02d}_{sanitize_name(stage_name)}"
        stage_path = ROOT / stage_folder_name

        if not stage_path.exists():
            total_folders += 1
        stage_path.mkdir(parents=True, exist_ok=True)

        for topic in topics:
            f, d = build_topic(stage_path, topic)
            total_files += f
            total_folders += d

        stage_table_rows.append(
            f"| {index:02d} | [{stage_name}](./{stage_folder_name}/) |"
        )

    # Write / refresh the root README.
    readme_path = ROOT / "README.md"
    readme_path.write_text(
        README_TEMPLATE.format(stage_table="\n".join(stage_table_rows)),
        encoding="utf-8",
    )

    print("[+] Cybersecurity roadmap architecture generated successfully.")
    print(f"    Root path        : {ROOT}")
    print(f"    Stages           : {len(ROADMAP)}")
    print(f"    New folders made : {total_folders}")
    print(f"    New files made   : {total_files}")
    print(f"    README written   : {readme_path}")


if __name__ == "__main__":
    main()
